-- Bảng Danh Mục
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten VARCHAR NOT NULL,
  slug VARCHAR NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bảng Sản Phẩm
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten VARCHAR NOT NULL,
  gia NUMERIC NOT NULL,
  giakm NUMERIC,
  photo VARCHAR,
  slug VARCHAR NOT NULL UNIQUE,
  description TEXT,
  category_slug VARCHAR REFERENCES public.categories(slug) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bảng Slideshow
CREATE TABLE public.slides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  photo VARCHAR NOT NULL,
  link VARCHAR,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bảng Cấu Hình
CREATE TABLE public.settings (
  key VARCHAR PRIMARY KEY,
  value TEXT NOT NULL
);

-- Thêm dữ liệu mẫu (Tùy chọn)
INSERT INTO public.categories (ten, slug) VALUES 
('Bia Nhập Khẩu', 'bia-nhap-khau'),
('Rượu Vang', 'ruou-vang');

INSERT INTO public.products (ten, gia, giakm, photo, slug, category_slug, description) VALUES 
('Bia Đen Belgium', 150000, NULL, '/belgium.jpg', 'bia-den-belgium', 'bia-nhap-khau', 'Bia đen đậm đà hương vị truyền thống Bỉ.'),
('Rượu Vang Đỏ Pháp', 350000, 299000, '/ruouvangdo.jpg', 'ruou-vang-do-phap', 'ruou-vang', 'Rượu vang đỏ cao cấp từ vùng Bordeaux.');
